apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: myblog-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      volumes:
      - name: pv-system-registry
        persistentVolumeClaim:
          claimName: pvc-system-registry
      containers:
        - name: registry
          image: registry
          ports:
          - containerPort: 5000
          volumeMounts:
          - name: pv-system-registry
            mountPath: /var/lib/registry
