kind: Namespace
apiVersion: v1
metadata:
  name: myblog-system
  labels:
    name: ingress-nginx
---
kind: Namespace
apiVersion: v1
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
---
kind: Namespace
apiVersion: v1
metadata:
  name: argocd
  labels:
    name: argocd
