apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /opt/kube/volumes/pv-jenkins-data
---