apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/kube/volumes/pv-prometheus-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-prometheus-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-log
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/kube/volumes/pv-prometheus-log
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-prometheus-log
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
