apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus1
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /opt/kube/volumes/pv-prometheus1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus2
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /opt/kube/volumes/pv-prometheus2
