apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redmine-db
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/kube/volumes/pv-redmine-db
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-redmine-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redmine-log
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/kube/volumes/pv-redmine-log
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-redmine-log
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
