apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-system-registry
  namespace: myblog-system
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/kube/volumes/pv-system-registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-system-registry
  namespace: myblog-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
