apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redmine1
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /opt/kube/volumes/pv-redmine1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redmine2
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /opt/kube/volumes/pv-redmine2
