apiVersion: v1
kind: Service
metadata:
  name: registry-svc
spec:
  selector:
    name: registry
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30004
    protocol: TCP
  externalIPs:
  - 192.168.11.21
  - 192.168.11.22
  type: NodePort
