apiVersion: v1
kind: Service
metadata:
  name: redmine-svc
spec:
  selector:
    name: redmine-app
  ports:
  - port: 10080
    targetPort: 9090
    nodePort: 30003
    protocol: TCP
  externalIPs:
  - 192.168.0.21
  - 192.168.0.22
  type: NodePort
